name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'  # Triggers on tags like v1.2.3

jobs:
  publish:
    permissions:
      id-token: write  # Required for authentication with pub.dev
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1